### ISSUE TITLE
Lint on change

### ISSUE THREAD

**Issue by elstgav** [elstgav/SublimeLinter-slim-lint#1]
SublimeLinter uses temp files to lint while you code. Problem is these temp files are created in a separate directory, so slim-lint can't do its automatic detection of the config file using the file path. We get around this by using the `--config` option with `slim-lint`. However, we can't supply the location of the rubocop config, so when slim-lint runs rubocop it resorts to its default configuration.

This leaves us two options:

1. Lint the actual file after its saved. This is less than ideal, as it slows down the linting process, and SublimeLinter will actually freeze SublimeText while it does its thing. Very annoying and cumbersome.
2. Modify `slim-lint` so that we can manually set the config path for rubocop. 

For now I'll pursue option 2.

**Comment by Zyphrax** [comment]
I noticed this issue, as soon as I correct one of the issues all linter errors are gone.

Couldn't you borrow the solution from Haml-Lint?
https://github.com/brigade/haml-lint

They must be having the same problem right?

**Comment by elstgav** [comment]
Released in v2.0.0 (64e1acba)
