### ISSUE TITLE
No Ruby script found in input error

### ISSUE THREAD

**Issue by maksimf** [elstgav/SublimeLinter-slim-lint#3]
I run ST3 on mac, where I already have SublimeLinter-rubocop installed, and added this lines to my SublimeLinter.sublime-settings:
```json
"paths": {
    "linux": [],
    "osx": [
        "/usr/local/opt/rbenv/bin",
        "/usr/local/opt/rbenv/shims"
    ],
    "windows": []
}
```

When I try to run slim-linter in debug mode I see the following command: `/usr/local/opt/rbenv/shims/ruby /usr/local/opt/rbenv/shims/slim-lint --version` which results in `ruby: no Ruby script found in input (LoadError)`. Whereas rubocop linter successfully uses command: `/usr/local/opt/rbenv/shims/ruby -S rubocop --version`. Note: there is no path to rubocop executable included, so, can you please change SublimeLinter-slim to the similar behaviour?

**Comment by maksimf** [comment]
I would have suggested a pull request to fix this issue, but I actually could not find where this behaviour is being set.

**Comment by elstgav** [comment]
Thanks for reporting this, it looks like a simple fix
